version: '3.8'
services:
  bank-db:
    image: postgres:17
    container_name: bank-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_accounts