spring:
  security:
    oauth2:
      client:
        registration:
          cash-service-client:
            client-id: cash-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: internal_api
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/bank-realm
  application:
    name: cash-service