server:
  port: 8082

spring:
  application:
    name: cash-service
  security:
    oauth2:
      client:
        registration:
          cash-service-client:
            client-id: cash-service
            client-secret: ${CASH_CLIENT_SECRET:secret}
            authorization-grant-type: client_credentials
            scope: internal_api

  config:
    import: "optional:configserver:http://localhost:8888"
