server:
  port: 8082

spring:
  application:
    name: cash-service
  security:
    oauth2:
      client:
        registration:
          cash-service-client:
            client-id: cash-service
            client-secret: ${CASH_CLIENT_SECRET:secret}
            authorization-grant-type: client_credentials
            scope: internal_api
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:9090/realms/bank-realm}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:9090/realms/bank-realm}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://localhost:9090/realms/bank-realm/protocol/openid-connect/certs}
