apiVersion: v1
kind: Secret
metadata:
  name: accounts-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}
  ACCOUNTS_CLIENT_SECRET: {{ .Values.oauth2Secrets.accountsClientSecret | quote }}
