apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cash-service
  template:
    metadata:
      labels:
        app: cash-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: cash-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: cash-service-config
            - secretRef:
                name: cash-service-secret
