{
 "title": "Bank Business Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ошибки Переводов (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(bank_transfer_failed_total)"
    }
   ]
  },
  {
   "title": "Ошибки Снятия Наличных (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(bank_cash_withdraw_failed_total)"
    }
   ]
  },
  {
   "title": "Сбои Уведомлений (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(bank_notification_failed_total)"
    }
   ]
  },
  {
   "title": "Динамика ошибок (Rate 5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(bank_transfer_failed_total[5m]))",
     "legendFormat": "Переводы"
    },
    {
     "expr": "sum(rate(bank_cash_withdraw_failed_total[5m]))",
     "legendFormat": "Снятие"
    },
    {
     "expr": "sum(rate(bank_notification_failed_total[5m]))",
     "legendFormat": "Уведомления"
    }
   ]
  }
 ]
}