apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["app-logs"]
        codec => json
        group_id => "logstash-group"
        auto_offset_reset => "earliest"
      }
    }
    filter {
      if [app] {
        mutate {
          add_field => { "service_name" => "%{app}" }
        }
      }
      mutate {
        remove_field => ["@version", "host"]
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "microservices-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }