apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 50000
        codec => json_lines
      }
    }
    filter {
      # Можно добавить фильтры по необходимости
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "microservices-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }