server:
  port: 8083

spring:
  application:
    name: transfer-service
  security:
    oauth2:
      client:
        registration:
          transfer-service-client:
            client-id: transfer-service
            client-secret: ${TRANSFER_CLIENT_SECRET:secret}
            authorization-grant-type: client_credentials
            scope: internal_api
