apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: notifications-service-config
