apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  OAUTH2_ISSUER_URI: {{ .Values.oauth2.issuerUri | quote }}
  OAUTH2_JWK_SET_URI: {{ .Values.oauth2.jwkSetUri | quote }}
  SERVICES_ACCOUNTS_URL: {{ .Values.services.accountsUrl | quote }}
  SERVICES_CASH_URL: {{ .Values.services.cashUrl | quote }}
  SERVICES_TRANSFER_URL: {{ .Values.services.transferUrl | quote }}
