apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-service-config
data:
  OAUTH2_ISSUER_URI: {{ .Values.oauth2.issuerUri | quote }}
  OAUTH2_JWK_SET_URI: {{ .Values.oauth2.jwkSetUri | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
